apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: dvwa
  name: dvwa
  namespace: dvwa
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dvwa
  type: ClusterIP
